const icons={search:'<circle cx="10.5" cy="10.5" r="7.5"/><path d="m16 16 5 5"/>',bag:'<path d="M5 7h14l2 15H3L5 7Z"/><path d="M8 9V5a4 4 0 0 1 8 0v4"/>',account:'<circle cx="12" cy="7" r="4"/><path d="M3 22v-3a9 9 0 0 1 18 0v3"/>',menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',leaf:'<path d="M21 3C10 3 3 8 4 15c1 7 13 7 17-12Z"/><path d="M3 22 17 8"/>',spark:'<path d="m15 2 2.2 6.8L23 11l-5.8 2.2L15 20l-2.2-6.8L7 11l5.8-2.2L15 2ZM5 14l1.2 3.8L10 19l-3.8 1.2L5 24l-1.2-3.8L0 19l3.8-1.2L5 14Z"/>',sun:'<circle cx="12" cy="12" r="5"/><path d="M12 1v2m0 18v2M1 12h2m18 0h2M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 25" aria-hidden="true">${icons[name]||icons.heart}</svg>`;
const header=document.getElementById('site-header');
if(header)header.innerHTML=`<div class="announcement"><p>Small rituals. Beautiful moments.</p><p>BEAUTY BEYOND ROUTINE</p><p>Your beauty journey starts here ♡</p></div><header class="header"><button class="hamburger icon-button" aria-label="Open menu" aria-controls="primary-navigation" aria-expanded="false">${icon('menu')}</button><a class="brand" href="index.html" aria-label="Maison Surga home"><img src="assets/logo.svg?v=2" alt="Maison Surga — Beauty Beyond Routine" width="230" height="85"></a><nav id="primary-navigation" aria-label="Main navigation"><a href="index.html#shop">Shop</a><a href="collection.html?category=skincare">Skincare</a><a href="collection.html?category=tools">Beauty Tools</a><a href="collection.html?category=makeup">Makeup</a><a href="collection.html?category=selfcare">Self-Care</a><a href="about.html">About</a><button class="mobile-nav-account" data-dialog="account-dialog" type="button">Account</button></nav><div class="header-actions"><button class="icon-button" data-dialog="search-dialog" aria-label="Search">${icon('search')}</button><button class="icon-button account-button" data-dialog="account-dialog" aria-label="Account">${icon('account')}</button><button class="icon-button" data-dialog="bag-dialog" aria-label="Shopping bag, 0 items">${icon('bag')}<span class="bag-count">(0)</span></button></div></header>`;
const footer=document.getElementById('site-footer');
if(footer)footer.innerHTML=`<footer class="footer"><div class="footer-top"><div class="footer-brand"><a href="index.html"><img src="assets/logo.svg?v=2" alt="Maison Surga — Beauty Beyond Routine" width="220" height="81"></a><p>A little care. A moment for you.</p></div><nav aria-label="Collections"><h3>Explore the edits</h3><a href="collection.html?category=skincare">Skincare</a><a href="collection.html?category=tools">Beauty Tools</a><a href="collection.html?category=makeup">Makeup</a><a href="collection.html?category=selfcare">Self-Care</a></nav><nav aria-label="About Maison Surga"><h3>Our world</h3><a href="about.html">Our story</a><a href="index.html#society">Surga Society</a><a href="collection.html">Coming soon</a></nav><nav aria-label="Help"><h3>Here to help</h3><a href="help.html#launch">Launch information</a><a href="help.html#delivery">Delivery & returns</a><a href="help.html#privacy">Privacy & cookies</a></nav></div><div class="footer-bottom"><p>© ${new Date().getFullYear()} Maison Surga. Beauty beyond routine.</p><p>United Kingdom · GBP (£)</p></div><p class="footer-note">Staging storefront. Images are AI-created editorial concepts; final products, packaging and catalogue may differ. Wix commerce and member flows are currently being tested.</p></footer>`;
document.body.insertAdjacentHTML('beforeend',`<dialog class="dialog" id="search-dialog" aria-labelledby="search-title"><div class="dialog-panel"><button class="dialog-close" aria-label="Close search">×</button><h2 id="search-title">Find your ritual.</h2><label for="search-input">Search our upcoming collection</label><input id="search-input" type="search" placeholder="Try skincare, brush or hair…" autocomplete="off"><div id="search-results" class="search-results" aria-live="polite"></div></div></dialog><dialog class="dialog" id="bag-dialog" aria-labelledby="bag-title"><div class="dialog-panel"><button class="dialog-close" aria-label="Close shopping bag">×</button><h2 id="bag-title">Your beauty bag</h2><div id="bag-content"><div class="bag-loading">Loading your bag…</div></div></div></dialog><dialog class="dialog" id="account-dialog" aria-labelledby="account-title"><div class="dialog-panel"><button class="dialog-close" aria-label="Close account">×</button><h2 id="account-title">Your Maison Surga.</h2><div id="account-content"><div class="bag-loading">Checking your account…</div></div></div></dialog>`);
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
const menu=document.querySelector('.hamburger'),nav=document.getElementById('primary-navigation');
function closeMenu(){nav?.classList.remove('open');menu?.setAttribute('aria-expanded','false');menu?.setAttribute('aria-label','Open menu');}
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu');});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.querySelector('.mobile-nav-account')?.addEventListener('click',closeMenu);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();const active=document.querySelector('dialog[open]');if(active){e.preventDefault();active.close();}}},true);
document.addEventListener('click',e=>{if(!e.target.closest('.header'))closeMenu();});
window.matchMedia('(min-width:761px)').addEventListener('change',closeMenu);
document.querySelectorAll('[data-dialog]').forEach(button=>button.addEventListener('click',()=>{const d=document.getElementById(button.dataset.dialog);d.showModal();document.body.classList.add('locked');if(d.id==='search-dialog')document.getElementById('search-input').focus();}));
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.dialog-close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close();});d.addEventListener('close',()=>document.body.classList.remove('locked'));});
const catalogue=[
{name:'Sonic Facial Cleansing Brush',tags:'skin skincare face cleansing brush',url:'product.html',image:'brush',detail:'Live Wix product'},
{name:'Skincare',tags:'skin skincare cleansing roller gua sha',url:'collection.html?category=skincare',image:'story',detail:'Explore the skincare edit'},
{name:'Beauty Tools',tags:'tools roller gua sha brushes',url:'collection.html?category=tools',image:'tools',detail:'Explore beauty tools'},
{name:'Makeup',tags:'makeup lips lashes colour',url:'collection.html?category=makeup',image:'hero',detail:'Explore the makeup edit'},
{name:'Self-Care',tags:'self care rest sleep ritual',url:'collection.html?category=selfcare',image:'hair',detail:'Explore self-care'}
];
function renderSearch(query=''){const found=catalogue.filter(item=>(item.name+' '+item.tags).toLowerCase().includes(query.toLowerCase().trim()));document.getElementById('search-results').innerHTML=found.length?found.map(item=>`<a href="${item.url}"><img src="assets/${item.image}.webp" alt=""><div>${item.name}<small>${item.detail}</small></div></a>`).join(''):'<p style="padding-top:20px">No matches yet. Try “brush”, “skin”, “makeup” or “self-care”.</p>';}
renderSearch();document.getElementById('search-input').addEventListener('input',e=>renderSearch(e.target.value));
const gallery=document.querySelector('.gallery-track');
if(gallery){const thumbs=[...document.querySelectorAll('.gallery-thumbs button')];thumbs.forEach((b,i)=>b.addEventListener('click',()=>gallery.scrollTo({left:gallery.clientWidth*i,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'})));gallery.addEventListener('scroll',()=>{const selected=Math.round(gallery.scrollLeft/gallery.clientWidth);thumbs.forEach((b,i)=>b.setAttribute('aria-current',String(i===selected)));},{passive:true});}
// Only retain attribution within the current tab's internal links. No analytics or storage is enabled.
const utms=new URLSearchParams();new URLSearchParams(location.search).forEach((v,k)=>{if(/^utm_(source|medium|campaign|term|content)$/.test(k))utms.set(k,v);});
document.addEventListener('click',event=>{const a=event.target.closest('a[href]');if(!a||!utms.size)return;const u=new URL(a.href,location.href);if(u.origin!==location.origin)return;utms.forEach((v,k)=>u.searchParams.set(k,v));a.href=u.href;});
// Commerce adapter: production integration may attach a consent-aware handler.
// Purchase must only be emitted by a verified checkout confirmation, never by a page visit.
window.maisonSurga={currency:'GBP',commerceEnabled:true,track(name,payload={}){if(!['ViewContent','AddToCart','InitiateCheckout','Purchase'].includes(name))return;window.dispatchEvent(new CustomEvent('surga:commerce',{detail:{name,payload}}));}};
if(document.body.dataset.page==='product')window.maisonSurga.track('ViewContent',{content_name:'Facial Cleansing Brush',status:'preview'});

if(window.MaisonWix){window.MaisonWix.initBag();window.MaisonWix.initAccount();window.MaisonWix.initCollectionPage();window.MaisonWix.initProductPage();}
